### ISSUE TITLE
Unable to install MarkLogic NiFi Connector 1.9.1.5 on NiFi 1.12 and Windows with OpenJDK 13

### ISSUE THREAD

**Issue by frankietsang** [marklogic/nifi#109]
Environment: 
- Windows Server 2016
- Nifi 1.12.1
- OpenJDK 13

After placed nifi-marklogic-nar-1.9.1.5.nar and nifi-marklogic-services-api-nar-1.9.1.5.nar in the extensions directory, the following errors were found in the log file:

`2021-02-03 13:14:05,523 INFO [NAR Auto-Loader] org.apache.nifi.nar.NarAutoLoaderTask Found .\extensions\nifi-marklogic-services-api-nar-1.9.1.5.nar in auto-load directory
2021-02-03 13:14:10,526 INFO [NAR Auto-Loader] org.apache.nifi.nar.StandardNarLoader Starting load process for 1 NARs...
2021-02-03 13:14:10,548 ERROR [NAR Auto-Loader] org.apache.nifi.nar.StandardNarLoader Error unpacking C:\Nifi\NIFI-1~1.1\.\extensions\nifi-marklogic-services-api-nar-1.9.1.5.nar
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1371)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at org.apache.nifi.nar.StandardNarLoader.unpack(StandardNarLoader.java:135)
	at org.apache.nifi.nar.StandardNarLoader.load(StandardNarLoader.java:79)
	at org.apache.nifi.nar.NarAutoLoaderTask.run(NarAutoLoaderTask.java:128)
	at java.base/java.lang.Thread.run(Thread.java:830)
2021-02-03 13:14:10,549 INFO [NAR Auto-Loader] org.apache.nifi.nar.StandardNarLoader No NARs were unpacked, nothing to do
2021-02-03 13:14:14,311 INFO [NAR Auto-Loader] org.apache.nifi.nar.NarAutoLoaderTask Found .\extensions\nifi-marklogic-nar-1.9.1.5.nar in auto-load directory
2021-02-03 13:14:16,097 INFO [pool-12-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Initiating checkpoint of FlowFile Repository
2021-02-03 13:14:16,441 INFO [pool-12-thread-1] o.a.n.wali.SequentialAccessWriteAheadLog Checkpointed Write-Ahead Log with 20223 Records and 0 Swap Files in 344 milliseconds (Stop-the-world time = 7 milliseconds), max Transaction ID 83774812
2021-02-03 13:14:16,441 INFO [pool-12-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Successfully checkpointed FlowFile Repository with 20223 records in 344 milliseconds
2021-02-03 13:14:19,313 INFO [NAR Auto-Loader] org.apache.nifi.nar.StandardNarLoader Starting load process for 1 NARs...
2021-02-03 13:14:19,331 ERROR [NAR Auto-Loader] org.apache.nifi.nar.StandardNarLoader Error unpacking C:\Nifi\NIFI-1~1.1\.\extensions\nifi-marklogic-nar-1.9.1.5.nar
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1371)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at org.apache.nifi.nar.StandardNarLoader.unpack(StandardNarLoader.java:135)
	at org.apache.nifi.nar.StandardNarLoader.load(StandardNarLoader.java:79)
	at org.apache.nifi.nar.NarAutoLoaderTask.run(NarAutoLoaderTask.java:128)
	at java.base/java.lang.Thread.run(Thread.java:830)
`
Performed another quick test on Nifi 1.11.4,, JDK 8 and Windows 10, there was no error from this environment.

**Comment by rjrudin** [comment]
Thanks @frankietsang - as noted in the README, we've developed and tested 1.9.1.5 on NiFi on 1.9.1, but we have not thoroughly tested it on more recent versions of NiFi. 

However, my guess is that Java 13 may be the culprit here. The NAR files were built using Java 8 (as NiFi 1.9.x requires Java 8), and I am guessing that something about the NAR format is handled differently between Java 8 and Java 13. 

Can you test NiFi 1.12 on Java 8 with the connector in your environment? It is unlikely that we will support Java 13 until, at a minimum, we release a new connector that is developed on top of NiFi 1.12.

**Comment by rjrudin** [comment]
@frankietsang I read through the NiFi release notes - https://cwiki.apache.org/confluence/display/NIFI/Release+Notes - and the only mention I see of Java versions there is Java 8 and Java 11. My conclusion from that is you should stick to running NiFi on Java 8 or 11. Thus, if you're able to run the ML connector on NiFi 1.12 and Java 8 or 11, please close this ticket, as I don't envision us providing any support on higher version of Java until NiFi  does so as well.

**Comment by frankietsang** [comment]
Thank you for the info.  I've tested it with Java 11 and it works.
