### ISSUE TITLE
PutMarkLogic Processor hangs, requires nifi server restart

### ISSUE THREAD

**Issue by sv091929** [marklogic/nifi#122]
Hello there,
We are facing an issue with MarkLogic Connector, some times the connection hangs for ever while writing records to Marklogic and we had to restart nifi server to resolve it. Is there a way to set timeout for the connection so that it should continue processing next records with new connection? It should retry or give up, we should not be expected to restart the server.  are there any connection properties to handle this, i do not find any in the documentation?

We are using NiFi Version 1.12.1 of Docker image and below connectors.
DefaultMarkLogicDatabaseClientService 1.9.1.7
PutMarkLogic 1.9.1.7

`2021-09-27 20:15:00,875 ERROR [Timer-Driven Process Thread-3] o.a.n.marklogic.processor.PutMarkLogic PutMarkLogic[id=712e0d0b-de3d-31f4-f619-2478488e8bed] Failed to properly initialize Processor. If still scheduled to run, NiFi will attempt to initialize and run the Processor again after the 'Administrative Yield Duration' has elapsed. Failure is due to com.marklogic.client.MarkLogicIOException: java.io.InterruptedIOException: com.marklogic.client.MarkLogicIOException: java.io.InterruptedIOException 
com.marklogic.client.MarkLogicIOException: java.io.InterruptedIOException 
	at com.marklogic.client.io.JacksonHandle.receiveContent(JacksonHandle.java:151) 
	at com.marklogic.client.io.JacksonHandle.receiveContent(JacksonHandle.java:48) 
	at com.marklogic.client.impl.OkHttpServices.getResource(OkHttpServices.java:3061) 
	at com.marklogic.client.datamovement.impl.DataMovementServices.readForestConfig(DataMovementServices.java:51) 
	at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.readForestConfig(DataMovementManagerImpl.java:160) 
	at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.getForestConfig(DataMovementManagerImpl.java:155) 
	at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.newWriteBatcher(DataMovementManagerImpl.java:103) 
	at org.apache.nifi.marklogic.processor.PutMarkLogic.onScheduled(PutMarkLogic.java:230) 
`

**Comment by rjrudin** [comment]
Closing due to lack of response - please reopen if this is still an issue and if you can provide answers for the questions above.
