### ISSUE TITLE
SSL for PutMarklogic processor not working

### ISSUE THREAD

**Issue by iowusu** [marklogic/nifi#24]
using the same SSL context service we were able to get HTTP calls working but the PutMarkLogic Processors throws this error
 java.lang.reflect.InvocationTargetException: null                                                                        
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                         
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                       
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                               
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                    
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:142)                         
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:130)                         
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:75)                          
        at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotation(ReflectionUtils.java:52)                           
        at org.apache.nifi.controller.StandardProcessorNode.lambda$initiateStart$4(StandardProcessorNode.java:1499)            
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                            
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)      
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                     
        at java.lang.Thread.run(Thread.java:748)                                                                               
Caused by: com.marklogic.client.MarkLogicIOException: java.net.SocketException: Connection reset                               
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:706)                                   
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:698)                                   
        at com.marklogic.client.impl.OkHttpServices.doGet(OkHttpServices.java:3982)                                            
        at com.marklogic.client.impl.OkHttpServices.access$1300(OkHttpServices.java:147)                                       
        at com.marklogic.client.impl.OkHttpServices$19.apply(OkHttpServices.java:3051)                                         
        at com.marklogic.client.impl.OkHttpServices$19.apply(OkHttpServices.java:3049)                                         
        at com.marklogic.client.impl.OkHttpServices.sendRequestWithRetry(OkHttpServices.java:728)                              
        at com.marklogic.client.impl.OkHttpServices.getResource(OkHttpServices.java:3054)                                      
        at com.marklogic.client.datamovement.impl.DataMovementServices.readForestConfig(DataMovementServices.java:51)          
        at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.readForestConfig(DataMovementManagerImpl.java:160)   
        at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.getForestConfig(DataMovementManagerImpl.java:155)    
        at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.newWriteBatcher(DataMovementManagerImpl.java:103)    
        at org.apache.nifi.marklogic.processor.PutMarkLogic.onScheduled(PutMarkLogic.java:233)                                 
        ... 15 common frames omitted

Note: The port of the database service controller matches the port of HTTP processor

**Comment by iowusu** [comment]
Use Case: This is required to enabled data go through secure communications that are encrypted. It is part of a regulation for Healthcare data that contain PII and PHI.

**Comment by ryanjdew** [comment]
Are you using a self-signed certificate?

**Comment by iowusu** [comment]
It fails for both self-signed Certificate and CA-signed certificate
