### ISSUE TITLE
NiFi to Marklogic Datahub ingestion process

### ISSUE THREAD

**Issue by dhillon21** [marklogic/nifi#36]
I am having some problems attempting to ingest data through apache nifi into data-hub. I keep getting errors when attempting to harmonize data in the datahub that is already ingested into a marklogic DB, basically circumventing the "input-flow" process of the datahub framework.
 
Process I have accomplished : 
1. Excel file into NiFi
2. NiFi into a MarkLogic DB, i.e staging DB

Process I need assistance with: 
1.  I have ingested data into a MarkLogic DB, i.e. staging DB,  **I would like to use the datahub to harmonize data from that DB and push that harmonized data into another MarkLogic DB, i.e final DB**.

I have been trying to look for some possible resources to help with this process but haven't been successful finding such material.  If someone could point me in the right direction or to an example of such a use case that would solve my issue. 

Thanks!

**Comment by ryanjdew** [comment]
If you use the latest release of the processors, you should be able to use the ExtensionCallMarkLogic processor to call the Data Hub REST endpoint for harmonization. 

You can see a sample cookbook recipe at https://marklogic.github.io/nifi/dhf-with-smart-mastering. The "ExtensionCallMarkLogic DHF Harmonize" section will be of most use to you.

**Comment by dhillon21** [comment]
Is there a way I can avoid NiFi for that process and just use the DataHub to do the harmonization work?

For example if I can somehow manipulate the collector plugin to access the MarkLogic staging DB, harmonize data, push data to MarkLogic final DB?

**Comment by dhillon21** [comment]
I am attempting to only use NiFi in the raw data ingestion process.  I do not want to use NiFi to manipulate any of the data if possible.

**Comment by ryanjdew** [comment]
Apologies if I'm not understanding the requirement right. The Data Hub harmonize REST API (https://marklogic.github.io/marklogic-data-hub/harmonize/rest/) takes an input of document indentifiers (or URIs) and that is what is being used in the recipe to run harmonization instead of a collector. The batch_success event from PutMarkLogic provides the URIs of the documents to be harmonized via the ExtensionCallMarkLogic processor. Is that what you're looking for?

**Comment by dhillon21** [comment]
> If you use the latest release of the processors, you should be able to use the ExtensionCallMarkLogic processor to call the Data Hub REST endpoint for harmonization.
> 
> You can see a sample cookbook recipe at https://marklogic.github.io/nifi/dhf-with-smart-mastering. The "ExtensionCallMarkLogic DHF Harmonize" section will be of most interest to you.

On preliminary review it seems this processor accesses an existing "harmonization flow" that I have created and the parameters for the processor are input DB as well as final DB correct?

This will accomplish what I need however it will utilize another NiFi Processor correct?

If that is the case at what point in the flow do i input that process.

Current Existing process flow below.
![nifi_mldb](https://user-images.githubusercontent.com/46113749/50845666-46412100-1322-11e9-8a5a-c2b309e9bc91.PNG)

**Comment by ryanjdew** [comment]
> On preliminary review it seems this processor accesses an existing "harmonization flow" that I have created and the parameters for the processor are input DB as well as final DB correct?

Yes.

> This will accomplish what I need however it will utilize another NiFi Processor correct?

Also correct.

You want to replace the BatchSuccess processor you have in your current flow with an ExtensionCallMarkLogic Processor and set the properties the same as decribed at https://marklogic.github.io/nifi/dhf-with-smart-mastering#extensioncallmarklogic-dhf-harmonize except make the values for `param:entity-name` and `param:flow-name` match your entity and flow names respectively.

**Comment by dhillon21** [comment]
Finally,  do the collector and writer plugins remain unedited?  Since I am using a NiFi processor to handle said plugin duties.

Also might be a silly question but what is the **_param: entity-name_** designated by?

**Comment by dhillon21** [comment]
Also will adding this processor still allow me to create a "staging DB" in MarkLogic with the raw data?

Or will this processor manipulate the data before ingestion into MarkLogic.

**Comment by ryanjdew** [comment]
No need to edit the plugins. The collector is simply ignored in this case and the writer is still being used for the document insert into final.

**param:entity-name** is the name of the entity which the harmonization flow is under.  e.g., entity-name: "Product" and flow-name: "ProductHarmonize"

The additional processor doesn't do any manipulation outside of MarkLogic. After the documents are inserted into staging via PutMarkLogic, it will make the REST call to harmonize on the documents in each successful batch of inserts.

**Comment by dhillon21** [comment]
I have a follow up question regarding this same scenario.  I am attempting to use this new processor and am getting a NullPointerException.  Am I setting this processor up correctly?  I am brand new to both Marklogic and NiFi.

Attached is configuration of **_ExtensionCallMarkLogic_** Processor as well as the subcategory **_extension name_** within said processor.  From what I was reading the extension name is the actual call to the endpoint if I am not mistaken.  I have also tried leading the request with keyword POST and has the same error.
![processordetails](https://user-images.githubusercontent.com/46113749/50982731-b2528f00-14b2-11e9-83a2-d9fd6a536897.PNG)
![processordetails_extensionname](https://user-images.githubusercontent.com/46113749/50982732-b2528f00-14b2-11e9-9576-06d690d5c8a3.PNG)



Thanks!

**Comment by ryanjdew** [comment]
You shouldn't provide the full URL in the Extension Name property. Extension Name should be set to 'ml:sjsFlow'. You can provide additional parameters using the + button on the top right side of the properties pane. 

Prefixing the property name with 'param:' will tell the processor it is a parameter to pass. e.g., You can add a parameter 'param:identifiers' and set the value to 'marklogic_testexcel' and so on.

Also, the Data Hub extension expects a JSON payload. You can set 'Payload Source' to 'Payload Properties', set 'Payload Format' to 'JSON', and set 'Payload' to '{}' (an empty JSON object). 

Finally, if you could provide the stack trace for the error you were getting it would be appreciated. Errors that we do throw should be more informative than a NullPointerException, so it is likely something that still needs to be addressed by us.

**Comment by dhillon21** [comment]
Below is the stack trace of the original error I was getting.  Now that i have corrected the above mentioned parameters I am getting another error involving the data-hub-framework extensions.

Will post stack trace for that error in next message.


2019-01-09 10:11:38,566 ERROR [Timer-Driven Process Thread-4] o.a.n.m.processor.ExtensionCallMarkLogic ExtensionCallMarkLogic[id=2ea538f4-0168-1000-26a9-5d55c9bdf581] ExtensionCallMarkLogic[id=2ea538f4-0168-1000-26a9-5d55c9bdf581] failed! Throwable exception java.lang.NullPointerException; rolling back session: java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.apache.nifi.marklogic.processor.ExtensionCallMarkLogic.onTrigger(ExtensionCallMarkLogic.java:206)
	at org.apache.nifi.marklogic.processor.ExtensionCallMarkLogic.onTrigger(ExtensionCallMarkLogic.java:167)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1165)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:203)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-01-09 10:11:38,592 ERROR [Timer-Driven Process Thread-4] o.a.n.m.processor.ExtensionCallMarkLogic ExtensionCallMarkLogic[id=2ea538f4-0168-1000-26a9-5d55c9bdf581] Failed to process session due to org.apache.nifi.processor.exception.ProcessException: java.lang.NullPointerException: org.apache.nifi.processor.exception.ProcessException: java.lang.NullPointerException
org.apache.nifi.processor.exception.ProcessException: java.lang.NullPointerException
	at org.apache.nifi.marklogic.processor.AbstractMarkLogicProcessor.handleThrowable(AbstractMarkLogicProcessor.java:251)
	at org.apache.nifi.marklogic.processor.ExtensionCallMarkLogic.onTrigger(ExtensionCallMarkLogic.java:227)
	at org.apache.nifi.marklogic.processor.ExtensionCallMarkLogic.onTrigger(ExtensionCallMarkLogic.java:167)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1165)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:203)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at org.apache.nifi.marklogic.processor.ExtensionCallMarkLogic.onTrigger(ExtensionCallMarkLogic.java:206)
	... 11 common frames omitted

**Comment by dhillon21** [comment]
This is stack trace of new error I am receiving along with a screenshot of updated processor configuration.

Also I am using Data Hub Quickstart UI to setup my harmonization flow.  Is this appropriate?

```
2019-01-10 09:29:42,453 ERROR [Timer-Driven Process Thread-8] o.a.n.m.processor.ExtensionCallMarkLogic ExtensionCallMarkLogic[id=2ea538f4-0168-1000-26a9-5d55c9bdf581] ExtensionCallMarkLogic[id=2ea538f4-0168-1000-26a9-5d55c9bdf581] failed! Throwable exception com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/ml:sjsFlow
: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: fn.error(null, 'RESTAPI-INVALIDREQ', -- Invalid request:  reason: cannot read module /MarkLogic/data-hub-framework/extensions/sjsflow.sjs for extension sjsflow . See the MarkLogic server error log for further detail.; rolling back session: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/ml:sjsFlow
: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: fn.error(null, 'RESTAPI-INVALIDREQ', -- Invalid request:  reason: cannot read module /MarkLogic/data-hub-framework/extensions/sjsflow.sjs for extension sjsflow . See the MarkLogic server error log for further detail.
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/ml:sjsFlow
: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: fn.error(null, 'RESTAPI-INVALIDREQ', -- Invalid request:  reason: cannot read module /MarkLogic/data-hub-framework/extensions/sjsflow.sjs for extension sjsflow . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4327)
	at com.marklogic.client.impl.OkHttpServices.postIteratedResourceImpl(OkHttpServices.java:3848)
	at com.marklogic.client.impl.OkHttpServices.postIteratedResource(OkHttpServices.java:3807)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:99)
	at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:95)
	at org.apache.nifi.marklogic.processor.ExtensionCallMarkLogic$ExtensionResourceManager.callService(ExtensionCallMarkLogic.java:244)
	at org.apache.nifi.marklogic.processor.ExtensionCallMarkLogic.onTrigger(ExtensionCallMarkLogic.java:218)
	at org.apache.nifi.marklogic.processor.ExtensionCallMarkLogic.onTrigger(ExtensionCallMarkLogic.java:167)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1165)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:203)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
![updated_processorconfig](https://user-images.githubusercontent.com/46113749/50987102-7a047e00-14bd-11e9-8494-63153a8b8eac.PNG)

**Comment by damonfeldman** [comment]
DHillion - you were also asking

> Is there a way I can avoid NiFi for that process and just use the DataHub to do the harmonization work?

and i want to clarify that yes, you can use other ways to harmonize data. The Data Hub fundamentally wants a bunch of REST calls to drive the harmonization. The driver making those rest calls could be any of
* NiFi
* An arbitrary program other than NiFi which makes REST calls in the proper form
* the MarkLogic Java API (a Java API that uses REST calls under the hood)
* the marklogic-gradle plugin that ships with the Data Hub Framework (which uses the Java API under the hood, so really still makes batched REST calls)

Here are the docs for ways to run harmonization: https://marklogic.github.io/marklogic-data-hub/harmonize/

The (second) easiest and most production ready is to us the marklogic-gradle plugin.

The absolute easiest is to run the harmonize activity from QuickStart (which uses the same code as the MarkLogic gradle plugin in the hub) but the QuickStart GUI is a "quick start" not intended for long term use or production use.

**Comment by dhillon21** [comment]
@damonfeldman Thank you for the clarification.

Does that mean the quickstart GUI is limited in its functionality when it comes to calling any harmonize flows you instantiate using it?

For example, if i was to create a harmonize flow in the quickstart GUI would I be able to call it using the "ExtensionCallMarkLogic" processor in NiFi?

**Comment by dhillon21** [comment]
As a follow up question:  When it comes to production purposes if I use the NiFi 'extensionCallMarkLogic' processor, where in the DHF (assuming not using Quickstart) am i making edits to the actual harmonization process to handle each specific case of harmonization?

Also is there a different version of DHF seperate from the "quickstart" version that needs to installed to be able to use this new 'extensioncallmarklogic' processor?

**Comment by rjrudin** [comment]
These questions are specific to DHF 4, and thus the new RunFlowMarkLogic processor (for DHF 5 flows) won't be relevant. 

For both DHF 4 and DHF 5, it's really necessary to use the FlowRunner Java class in the DHF Java API to run a flow. There's logic in the DHF Java API that is important to running a flow that you will miss out on if trying to run a flow by hitting HTTP endpoints directly in DHF. 

You mentioned early on that: "I am attempting to only use NiFi in the raw data ingestion process. I do not want to use NiFi to manipulate any of the data if possible."

That is the right goal with DHF 4 - use PutMarkLogic to ingest data into ML via NiFi, and then follow the DHF 4 docs for running a flow, which will likely involve either using QuickStart or Gradle.
