### ISSUE TITLE
Intermittent CSV failures when using PutMarkLogicRecord

### ISSUE THREAD

**Issue by rjrudin** [marklogic/nifi#37]
I'll provide more detail soon - hopefully both the template and a sample file (trying to narrow down the sample file that will reliably produce this error). But getting this message at odd times while ingesting a CSV file using GetFile -> SplitText -> PutMarkLogicRecord:

```
2019-01-08 12:46:02,751 ERROR [Timer-Driven Process Thread-2] o.a.n.m.processor.PutMarkLogicRecord PutMarkLogicRecord[id=2ae912b0-0168-1000-5376-08be55e65e7c] PutMarkLogicRecord[id=2ae912b0-0168-1000-5376-08be55e65e7c] failed to process session due to java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 307) invalid char between encapsulated token and delimiter; Processor Administratively Yielded for 1 sec: java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 307) invalid char between encapsulated token and delimiter
java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 307) invalid char between encapsulated token and delimiter
	at org.apache.commons.csv.CSVParser$1.getNextRecord(CSVParser.java:530)
	at org.apache.commons.csv.CSVParser$1.hasNext(CSVParser.java:540)
	at org.apache.nifi.csv.CSVRecordReader.nextRecord(CSVRecordReader.java:80)
	at org.apache.nifi.serialization.RecordReader.nextRecord(RecordReader.java:50)
	at org.apache.nifi.marklogic.processor.PutMarkLogicRecord.onTrigger(PutMarkLogicRecord.java:155)
```

I am not certain if a record is actually present, and I'm wondering if it's getting whitespace, or if there's really a bad row. Would help a lot if the error message included the record being read. 

Couple other issues I'm seeing when this happens:

1. More documents are created in ML than expected; almost as though a batch from SplitText is getting reprocessed
1. The queue from SplitText to PutMarkLogicRecord gets a FlowFile stuck in it; I can't delete it or empty it; have to restart NiFi, and then it still shows up, but I can at least empty it

**Comment by rjrudin** [comment]
@ryanjdew Figured it out. The test file I have has some "\" symbols in it, and the CSVReader was using that as the default escape character. I changed the escape character to "^", which doesn't exist in the test file, and the issue went away. 

This will be an important point for documenting though - that the escape character, which is required, must be properly used in the CSV file or should not exist. mlcp did not have any issue with the file.
