### ISSUE TITLE
DeleteMarkLogic processor not clearing upstream queues or outputting success

### ISSUE THREAD

**Issue by diamondp161** [marklogic/nifi#91]
DeleteMarkLogic processor v1.8.0.3 does not seem to output anything on success and it doesn't always properly clear the upstream queue. Haven't been able to consistently reproduce the upstream queue issue - sometimes it clears the file and other times it is 'stuck' showing as Queued but then NiFi tells me the queue is empty. See attached for a template of my test flow that is producing the issue.
![image](https://user-images.githubusercontent.com/68124438/90254281-7e6ae880-de10-11ea-81a3-cf714c916857.png)

[deleteMLexample.zip](https://github.com/marklogic/nifi/files/5074542/deleteMLexample.zip)

Here's all we get in the app.log:
`2020-08-14 09:24:51,547 INFO [pool-12-thread-1] o.a.n.wali.SequentialAccessWriteAheadLog Checkpointed Write-Ahead Log with 2 Records and 0 Swap Files in 200 milliseconds (Stop-the-world time = 193 milliseconds), max Transaction ID 7001198
2020-08-14 09:24:51,547 INFO [pool-12-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Successfully checkpointed FlowFile Repository with 2 records in 200 milliseconds
2020-08-14 09:24:53,336 INFO [NiFi Web Server-95] o.a.n.c.s.StandardProcessScheduler Starting DeleteMarkLogic[id=c87e2746-0173-1000-e3a4-d63d259856c9]
2020-08-14 09:24:53,336 INFO [NiFi Web Server-95] o.a.n.controller.StandardProcessorNode Starting DeleteMarkLogic[id=c87e2746-0173-1000-e3a4-d63d259856c9]
2020-08-14 09:24:53,338 INFO [Timer-Driven Process Thread-13] o.a.n.c.s.TimerDrivenSchedulingAgent Scheduled DeleteMarkLogic[id=c87e2746-0173-1000-e3a4-d63d259856c9] to run with 1 threads
2020-08-14 09:24:53,630 INFO [Timer-Driven Process Thread-14] c.m.c.datamovement.impl.QueryBatcherImpl (withForestConfig) Using forests on [server1, server2, server3] hosts for "data-hub-STAGING"
2020-08-14 09:24:53,639 INFO [Timer-Driven Process Thread-14] c.m.c.datamovement.impl.QueryBatcherImpl Starting job batchSize=100, threadCount=32, onUrisReady listeners=3, failure listeners=4
2020-08-14 09:24:53,738 INFO [Flow Service Tasks Thread-1] o.a.nifi.controller.StandardFlowService Saved flow controller org.apache.nifi.controller.FlowController@712f4c4f // Another save pending = false
2020-08-14 09:24:55,761 INFO [Thread-24] c.m.c.datamovement.impl.QueryBatcherImpl Job complete, jobBatchNumber=9, jobResultsSoFar=0
2020-08-14 09:24:55,761 INFO [Timer-Driven Process Thread-14] c.m.c.datamovement.impl.QueryBatcherImpl Job complete, jobBatchNumber=9, jobResultsSoFar=0`

**Comment by diamondp161** [comment]
Any update on this?

**Comment by ghassennasri** [comment]
MarkLogicDelete processor inherits from QueryMarkLogic processor overriding buildQueryBatchListener method to return a DeleteListener instead of returning a QueryBatchListener.

When initiating the flow, the onTrigger() event handler of the MarkLogicDelete processor will be invoking the parent handler so as to collect documents URIs satisfying the provided query (these URIs represents documents to be deleted). The onTrigger() handler of QueryMarklogic processor  gets the original flowFile from the session; 

if (context.hasIncomingConnection()) {//From QueryMarklogic.onTrigger()
    input = session.get();
} else {
    input = null;
} 

and use it to get some attributes from the flowFile (attributes related to stateIndex and queryType)Before queryBatcher completion, onUrisReady callback is triggered every time URIs get collected by a thread of queryBatcher(basing on DMSDK)  

On success event processEvent() method of the inner class DeleteMarkLogic.NiFiDeleteListener is the callback of onUrisReady ;

queryBatcher.onUrisReady(batchListener); //From QueryMarklogic.onTrigger()

In the method processEvent(), a new flowFiles is created for each collected URI and get transferred to SUCCESS destination.

The session.commit() call following the creation and transfer of new flowFiles will throw an Exception at the first call (the first thread of queryBatcher having collected Uris and entering the NiFiDeleteListener.processEvent() to perform deletion from MarkLogic, create new FolwFiles and transfer them to success)  ;

org.apache.nifi.processor.exception.FlowFileHandlingException: StandardFlowFileRecord[uuid=5d423425-feaa-4812-babb-9bb3c8ec7418,claim=,offset=0,name=5d423425-feaa-4812-babb-9bb3c8ec7418,size=0] transfer relationship not specified
        at org.apache.nifi.controller.repository.StandardProcessSession.checkpoint(StandardProcessSession.java:273)
        at org.apache.nifi.controller.repository.StandardProcessSession.commit(StandardProcessSession.java:346)
        at org.apache.nifi.marklogic.processor.DeleteMarkLogic$NiFiDeleteListener.processEvent(DeleteMarkLogic.java:124)
        at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:674)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**The Exception is due to the Original upstream flowFile not having a destination set (destination=null) as there is no statement transferring the original flowFile to a destination or removing it from the session at least.**

I think the Original upstream flowFile should be removed from the session before calling session.commit() to persist the new flowFiles in the NiFiDeleteListener.processEvent().

The impact of this Error is the DeleteMarkLogic queue not dequeuing flowFiles and that will also prevent deleting or changing the destination of the source component as if MarkLogicDelete processor keeps holding a handle of the original flowFile.

6de2932e.png
![image](https://user-images.githubusercontent.com/58290527/96465403-36f64380-1229-11eb-9476-de96d82e1505.png)


This bug is impacting the DeleteMarkLogic processor v1.8.0.3.
Internal support case reference: https://help.marklogic.com/staff/Tickets/Ticket/View/29997

**Comment by diamondp161** [comment]
Is anyone working on this?

**Comment by rjrudin** [comment]
This will be in the upcoming 1.9.1.5 release
